package v1

import (
	"time"

	"clickhouse-ops/internal/api/auth"
	"clickhouse-ops/internal/api/middleware"
	"clickhouse-ops/internal/api/repository"
	"clickhouse-ops/internal/api/v1/handlers"
	_ "clickhouse-ops/internal/api/docs" // swagger docs - generated by swag init
	"clickhouse-ops/internal/db"
	"clickhouse-ops/internal/logger"
	"github.com/gin-gonic/gin"
)

// RouterConfig holds router configuration
type RouterConfig struct {
	JWTSecretKey     string
	JWTTokenDuration time.Duration // token duration
	RateLimitRPS     float64
	RateLimitBurst   int
	Logger           *logger.Logger
}

// SetupRouter sets up API v1 routes
func SetupRouter(cfg RouterConfig) *gin.Engine {
	router := gin.New()

	// Global middleware
	router.Use(gin.Recovery())                                    // Panic recovery
	router.Use(middleware.TracingMiddleware())                    // Tracing
	router.Use(middleware.LoggingMiddleware(cfg.Logger))          // Logging

	// Optional rate limiting
	if cfg.RateLimitRPS > 0 {
		rateLimiter := middleware.NewRateLimiter(cfg.RateLimitRPS, cfg.RateLimitBurst)
		router.Use(rateLimiter.RateLimitMiddleware())
	}

	// CORS middleware
	router.Use(func(c *gin.Context) {
		c.Header("Access-Control-Allow-Origin", "*")
		c.Header("Access-Control-Allow-Methods", "GET, POST, PUT, DELETE, OPTIONS")
		c.Header("Access-Control-Allow-Headers", "Content-Type, Authorization, X-Trace-ID")

		if c.Request.Method == "OPTIONS" {
			c.AbortWithStatus(204)
			return
		}

		c.Next()
	})

	// Initialize JWT manager
	jwtManager := auth.NewJWTManager(
		cfg.JWTSecretKey,
		cfg.JWTTokenDuration,
	)

	// Initialize user repository
	dbInstance := db.GetInstance()
	if dbInstance == nil {
		cfg.Logger.Error("Database instance is not available")
		// Continue without user repository - handlers will handle errors
	}
	
	var userRepo *repository.UserRepository
	if dbInstance != nil {
		gormDB := dbInstance.GetGormDB()
		if gormDB == nil {
			cfg.Logger.Error("GORM database instance is not available")
		} else {
			userRepo = repository.NewUserRepository(gormDB)
		}
	}

	// Initialize handlers
	authHandler := handlers.NewAuthHandler(jwtManager, userRepo, cfg.Logger)
	healthHandler := handlers.NewHealthHandler()
	metricsHandler, err := handlers.NewMetricsHandler(cfg.Logger)
	if err != nil {
		cfg.Logger.Errorf("Failed to initialize metrics handler: %v", err)
		// Continue without metrics handler - endpoints will return errors
	}

	// Health check endpoint (no auth required)
	router.GET("/healthz", healthHandler.Healthz)

	// API v1 routes
	v1 := router.Group("/api/v1")
	{
		// Auth routes (no auth required)
		auth := v1.Group("/auth")
		{
			auth.POST("/login", authHandler.Login)
			auth.POST("/register", authHandler.Register)
			auth.GET("/me", middleware.AuthMiddleware(jwtManager), authHandler.GetUserInfo)
		}

		// Protected routes
		protected := v1.Group("/")
		protected.Use(middleware.AuthMiddleware(jwtManager))
		{
			// Metrics routes
			if metricsHandler != nil {
				metrics := protected.Group("/metrics")
				{
					metrics.GET("/nodes", metricsHandler.GetAvailableNodes)
					metrics.GET("/current", metricsHandler.GetCurrentMetrics)
					metrics.GET("/stream", metricsHandler.StreamMetrics)
				}
			}
		}
	}

	return router
}
