services:
  chops_front:
    container_name: chops_front-prod
    build:
      context: ./frontend
      dockerfile: build/docker/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - chops_app
    networks:
      - ch_ops
  chops_app:
    container_name: chops_app-prod
    build:
      context: ./agent
      dockerfile: ./Dockerfile
      target: production
    ports:
      - "8080:8080"
    depends_on:
      chops_db:
        condition: service_healthy
      chops_ch:
        condition: service_started
      chops_ch_2:
        condition: service_started
    networks:
      - ch_ops
  chops_db:
    image: postgres:13.11
    container_name: chops_db
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_PASSWORD=12345
      - POSTGRES_USER=ops
      - POSTGRES_DB=public
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ops -d public" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5436:5432
    logging:
      options:
        max-size: 10m
        max-file: "3"
    networks:
      - ch_ops
  chops_ch:
    image: clickhouse/clickhouse-server:latest
    container_name: chops_ch
    ports:
      - "8121:8123"
      - "9005:9000"
    volumes:
      - ./.config/clickhouse/config.xml:/etc/clickhouse-server/config.xml
      - ./.config/clickhouse/users.xml:/etc/clickhouse-server/users.xml
      - ./.config/clickhouse/config.d:/etc/clickhouse-server/config.d
      - ./.config/clickhouse/users.d:/etc/clickhouse-server/users.d
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - ch_ops
  chops_ch_2:
    image: clickhouse/clickhouse-server:latest
    container_name: chops_ch_2
    ports:
      - "8120:8123"
      - "9006:9000"
    volumes:
      - ./.config/clickhouse/config.xml:/etc/clickhouse-server/config.xml
      - ./.config/clickhouse/users.xml:/etc/clickhouse-server/users.xml
      - ./.config/clickhouse/config.d:/etc/clickhouse-server/config.d
      - ./.config/clickhouse/users.d:/etc/clickhouse-server/users.d
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - ch_ops
networks:
  ch_ops:
    name: ch_ops