package api

import (
	"time"

	"clickhouse-ops/internal/api/auth"
	_ "clickhouse-ops/internal/api/docs" // swagger docs - generated by swag init
	"clickhouse-ops/internal/api/middleware"
	clickhouseHandlers "clickhouse-ops/internal/api/v1/handlers/clickhouse"
	systemHandlers "clickhouse-ops/internal/api/v1/handlers/system"
	chrepo "clickhouse-ops/internal/clickhouse/repository"
	"clickhouse-ops/internal/config"
	"clickhouse-ops/internal/db/repository"
	"clickhouse-ops/internal/logger"
	"clickhouse-ops/internal/rbac"

	"github.com/gin-gonic/gin"
)

// RouterConfig holds router configuration
type RouterConfig struct {
	JWTSecretKey     string
	JWTTokenDuration time.Duration // token duration
	RateLimitRPS     float64
	RateLimitBurst   int
	Logger           *logger.Logger
	Config           *config.Config
}

// RouterWithHandlers holds router and handlers for cleanup in tests
type RouterWithHandlers struct {
	Router          *gin.Engine
	MetricsHandler  *clickhouseHandlers.MetricsHandler
	QueryLogHandler *clickhouseHandlers.QueryLogHandler
	ProcessHandler  *clickhouseHandlers.ProcessHandler
}

// SetupRouter sets up API v1 routes
func SetupRouter(cfg RouterConfig) *gin.Engine {
	router, _ := SetupRouterWithHandlers(cfg)
	return router
}

// SetupRouterWithHandlers sets up API v1 routes and returns handlers for cleanup
func SetupRouterWithHandlers(cfg RouterConfig) (*gin.Engine, *RouterWithHandlers) {
	router := gin.New()

	setupGlobalMiddleware(router, cfg)
	jwtManager := initializeJWTManager(cfg)
	handlers := initializeHandlers(cfg)
	setupRoutes(router, jwtManager, handlers)

	return router, &RouterWithHandlers{
		Router:          router,
		MetricsHandler:  handlers.MetricsHandler,
		QueryLogHandler: handlers.QueryLogHandler,
		ProcessHandler:  handlers.ProcessHandler,
	}
}

// setupGlobalMiddleware configures global middleware for the router
func setupGlobalMiddleware(router *gin.Engine, cfg RouterConfig) {
	// Panic recovery
	router.Use(gin.Recovery())

	// Tracing
	router.Use(middleware.TracingMiddleware())

	// Logging
	router.Use(middleware.LoggingMiddleware(cfg.Logger))

	// Optional rate limiting
	if cfg.RateLimitRPS > 0 {
		rateLimiter := middleware.NewRateLimiter(cfg.RateLimitRPS, cfg.RateLimitBurst)
		router.Use(rateLimiter.RateLimitMiddleware())
	}

	// CORS
	setupCORS(router)
}

// setupCORS configures CORS middleware
func setupCORS(router *gin.Engine) {
	router.Use(func(c *gin.Context) {
		c.Header("Access-Control-Allow-Origin", "*")
		c.Header("Access-Control-Allow-Methods", "GET, POST, PUT, DELETE, OPTIONS")
		c.Header("Access-Control-Allow-Headers", "Content-Type, Authorization, X-Trace-ID")

		if c.Request.Method == "OPTIONS" {
			c.AbortWithStatus(204)
			return
		}

		c.Next()
	})
}

// initializeJWTManager creates and returns JWT manager
func initializeJWTManager(cfg RouterConfig) *auth.JWTManager {
	return auth.NewJWTManager(
		cfg.JWTSecretKey,
		cfg.JWTTokenDuration,
	)
}

// handlersContainer holds all initialized handlers
type handlersContainer struct {
	AuthHandler        *systemHandlers.AuthHandler
	HealthHandler      *systemHandlers.HealthHandler
	MetricsHandler     *clickhouseHandlers.MetricsHandler
	QueryLogHandler    *clickhouseHandlers.QueryLogHandler
	ProcessHandler     *clickhouseHandlers.ProcessHandler
	UsersHandler       *clickhouseHandlers.UsersHandler
	ProfilesHandler    *clickhouseHandlers.ProfilesHandler
	RolesHandler       *clickhouseHandlers.RolesHandler
	AccessScopeHandler *clickhouseHandlers.AccessScopeHandler
	BackupHandler      *clickhouseHandlers.BackupHandler
	SchemasHandler     *clickhouseHandlers.SchemasHandler
	TablesHandler      *clickhouseHandlers.TablesHandler
	ColumnsHandler     *clickhouseHandlers.ColumnsHandler
	SettingsHandler    *clickhouseHandlers.SettingsHandler
	RBACRepo           *repository.RBACRepository
	RBACAdminHandler   *systemHandlers.RBACAdminHandler
}

// initializeHandlers creates and initializes all handlers
func initializeHandlers(cfg RouterConfig) *handlersContainer {
	container := &handlersContainer{}

	// Initialize auth handler
	authHandler, err := systemHandlers.NewAuthHandler(initializeJWTManager(cfg), cfg.Logger)
	if err != nil {
		cfg.Logger.Errorf("Failed to initialize auth handler: %v", err)
	}
	container.AuthHandler = authHandler

	rbacRepo, err := repository.NewRBACRepository()
	if err != nil {
		cfg.Logger.Errorf("Failed to initialize RBAC repository: %v", err)
	} else {
		container.RBACRepo = rbacRepo
	}
	container.RBACAdminHandler = systemHandlers.NewRBACAdminHandler(rbacRepo, cfg.Logger)

	// Initialize health handler
	container.HealthHandler = systemHandlers.NewHealthHandler()

	// Initialize metrics handler
	metricsHandler, err := clickhouseHandlers.NewMetricsHandler(cfg.Logger, cfg.Config)
	if err != nil {
		cfg.Logger.Errorf("Failed to initialize metrics handler: %v", err)
	}
	container.MetricsHandler = metricsHandler

	// Initialize query log handler
	queryLogHandler, err := clickhouseHandlers.NewQueryLogHandler(cfg.Logger, cfg.Config)
	if err != nil {
		cfg.Logger.Errorf("Failed to initialize query log handler: %v", err)
	}
	container.QueryLogHandler = queryLogHandler

	// Initialize process handler
	processHandler, err := clickhouseHandlers.NewProcessHandler(cfg.Logger, cfg.Config)
	if err != nil {
		cfg.Logger.Errorf("Failed to initialize process handler: %v", err)
	}
	container.ProcessHandler = processHandler

	// Initialize users handler
	usersHandler, err := clickhouseHandlers.NewUsersHandler(cfg.Logger, cfg.Config)
	if err != nil {
		cfg.Logger.Errorf("Failed to initialize users handler: %v", err)
	}
	container.UsersHandler = usersHandler

	// Initialize profiles handler
	profilesHandler, err := clickhouseHandlers.NewProfilesHandler(cfg.Logger, cfg.Config)
	if err != nil {
		cfg.Logger.Errorf("Failed to initialize profiles handler: %v", err)
	}
	container.ProfilesHandler = profilesHandler

	// Initialize roles handler
	rolesHandler, err := clickhouseHandlers.NewRolesHandler(cfg.Logger, cfg.Config)
	if err != nil {
		cfg.Logger.Errorf("Failed to initialize roles handler: %v", err)
	}
	container.RolesHandler = rolesHandler

	// Initialize access scope handler
	accessScopeHandler, err := clickhouseHandlers.NewAccessScopeHandler(cfg.Logger, cfg.Config)
	if err != nil {
		cfg.Logger.Errorf("Failed to initialize access scope handler: %v", err)
	}
	container.AccessScopeHandler = accessScopeHandler

	// Initialize backup handler
	backupHandler, err := clickhouseHandlers.NewBackupHandler(cfg.Logger, cfg.Config)
	if err != nil {
		cfg.Logger.Errorf("Failed to initialize backup handler: %v", err)
	}
	container.BackupHandler = backupHandler

	// Initialize schemas handler
	schemasHandler, err := clickhouseHandlers.NewSchemasHandler(cfg.Logger, cfg.Config)
	if err != nil {
		cfg.Logger.Errorf("Failed to initialize schemas handler: %v", err)
	}
	container.SchemasHandler = schemasHandler

	// Initialize tables handler
	tablesHandler, err := clickhouseHandlers.NewTablesHandler(cfg.Logger, cfg.Config)
	if err != nil {
		cfg.Logger.Errorf("Failed to initialize tables handler: %v", err)
	}
	container.TablesHandler = tablesHandler

	// Initialize columns handler
	columnsHandler, err := clickhouseHandlers.NewColumnsHandler(cfg.Logger, cfg.Config)
	if err != nil {
		cfg.Logger.Errorf("Failed to initialize columns handler: %v", err)
	}
	container.ColumnsHandler = columnsHandler

	// Initialize settings repository and handlers (shared repository)
	settingsRepo, err := chrepo.NewSettingsRepository(cfg.Config, cfg.Logger)
	if err != nil {
		cfg.Logger.Errorf("Failed to initialize settings repository: %v", err)
	} else {
		container.SettingsHandler = clickhouseHandlers.NewSettingsHandlerWithRepository(settingsRepo, cfg.Logger)
	}

	return container
}

// setupRoutes configures all API routes
func setupRoutes(router *gin.Engine, jwtManager *auth.JWTManager, handlers *handlersContainer) {
	// Health check endpoint (no auth required)
	if handlers.HealthHandler != nil {
		router.GET("/healthz", handlers.HealthHandler.Healthz)
	}

	// API v1 routes
	v1 := router.Group("/api/v1")
	{
		setupAuthRoutes(v1, jwtManager, handlers)
		setupProtectedRoutes(v1, jwtManager, handlers)
	}
}

// setupAuthRoutes configures authentication routes
func setupAuthRoutes(v1 *gin.RouterGroup, jwtManager *auth.JWTManager, handlers *handlersContainer) {
	if handlers.AuthHandler == nil {
		return
	}

	auth := v1.Group("/auth")
	{
		auth.POST("/login", handlers.AuthHandler.Login)
		auth.POST("/register", handlers.AuthHandler.Register)

		meHandlers := []gin.HandlerFunc{middleware.AuthMiddleware(jwtManager)}
		if handlers.RBACRepo != nil {
			meHandlers = append(meHandlers, middleware.LoadUserPermissions(handlers.RBACRepo), middleware.RequirePermission(rbac.PermAuthMe))
		}
		meHandlers = append(meHandlers, handlers.AuthHandler.GetUserInfo)
		auth.GET("/me", meHandlers...)
	}
}

// setupProtectedRoutes configures protected API routes
func setupProtectedRoutes(v1 *gin.RouterGroup, jwtManager *auth.JWTManager, handlers *handlersContainer) {
	protected := v1.Group("/")
	protected.Use(middleware.AuthMiddleware(jwtManager))
	if handlers.RBACRepo != nil {
		protected.Use(middleware.LoadUserPermissions(handlers.RBACRepo))
	}
	{
		setupSystemRBACRoutes(protected, handlers)
		setupMetricsRoutes(protected, handlers)
		setupQueryLogRoutes(protected, handlers)
		setupProcessRoutes(protected, handlers)
		setupUsersRoutes(protected, handlers)
		setupProfilesRoutes(protected, handlers)
		setupRolesRoutes(protected, handlers)
		setupAccessScopeRoutes(protected, handlers)
		setupBackupRoutes(protected, handlers)
		setupSchemasRoutes(protected, handlers)
		setupTablesRoutes(protected, handlers)
		setupColumnsRoutes(protected, handlers)
		setupSettingsRoutes(protected, handlers)
	}
}

// setupSystemRBACRoutes registers system role and permission management APIs.
func setupSystemRBACRoutes(protected *gin.RouterGroup, handlers *handlersContainer) {
	if handlers.RBACAdminHandler == nil {
		return
	}

	sys := protected.Group("/system")
	{
		sys.POST("/roles", middleware.RequirePermission(rbac.PermSystemRolesCreate), handlers.RBACAdminHandler.CreateRole)
		sys.GET("/roles", middleware.RequirePermission(rbac.PermSystemRolesList), handlers.RBACAdminHandler.ListRoles)
		sys.GET("/roles/:id", middleware.RequirePermission(rbac.PermSystemRolesGet), handlers.RBACAdminHandler.GetRole)
		sys.DELETE("/roles/:id", middleware.RequirePermission(rbac.PermSystemRolesDelete), handlers.RBACAdminHandler.DeleteRole)
		sys.PUT("/roles/:id/permissions", middleware.RequirePermission(rbac.PermSystemRolesSetPermissions), handlers.RBACAdminHandler.SetRolePermissions)
		sys.GET("/users", middleware.RequirePermission(rbac.PermSystemUsersList), handlers.RBACAdminHandler.ListSystemUsers)
		sys.PUT("/users/:id/active", middleware.RequirePermission(rbac.PermSystemUsersSetActive), handlers.RBACAdminHandler.SetUserActive)
		sys.PUT("/users/:id/role", middleware.RequirePermission(rbac.PermSystemUsersSetRole), handlers.RBACAdminHandler.AssignUserRole)
		sys.GET("/permissions", middleware.RequirePermission(rbac.PermSystemPermissionsList), handlers.RBACAdminHandler.ListPermissions)
	}
}

// setupMetricsRoutes configures metrics endpoints
func setupMetricsRoutes(protected *gin.RouterGroup, handlers *handlersContainer) {
	if handlers.MetricsHandler == nil {
		return
	}

	metrics := protected.Group("/clickhouse/metrics")
	{
		metrics.GET("/nodes", middleware.RequirePermission(rbac.PermClickhouseMetricsNodes), handlers.MetricsHandler.GetAvailableNodes)
		metrics.GET("/current", middleware.RequirePermission(rbac.PermClickhouseMetricsCurrent), handlers.MetricsHandler.GetCurrentMetrics)
		metrics.GET("/stream", middleware.RequirePermission(rbac.PermClickhouseMetricsStream), handlers.MetricsHandler.StreamMetrics)
		metrics.GET("/series", middleware.RequirePermission(rbac.PermClickhouseMetricsSeries), handlers.MetricsHandler.GetMetricSeries)
		metrics.GET("/server-info", middleware.RequirePermission(rbac.PermClickhouseMetricsServerInfo), handlers.MetricsHandler.GetServerInfo)
	}
}

// setupQueryLogRoutes configures query log endpoints
func setupQueryLogRoutes(protected *gin.RouterGroup, handlers *handlersContainer) {
	if handlers.QueryLogHandler == nil {
		return
	}

	queryLog := protected.Group("/clickhouse/query-log")
	{
		queryLog.GET("", middleware.RequirePermission(rbac.PermClickhouseQueryLogList), handlers.QueryLogHandler.ListQueryLog)
		queryLog.GET("/stats", middleware.RequirePermission(rbac.PermClickhouseQueryLogStats), handlers.QueryLogHandler.GetQueryLogStats)
		queryLog.GET("/stats/stream", middleware.RequirePermission(rbac.PermClickhouseQueryLogStatsStream), handlers.QueryLogHandler.StreamQueryLogStats)
	}
}

// setupProcessRoutes configures process management endpoints
func setupProcessRoutes(protected *gin.RouterGroup, handlers *handlersContainer) {
	if handlers.ProcessHandler == nil {
		return
	}

	processes := protected.Group("/clickhouse/processes")
	{
		processes.GET("", middleware.RequirePermission(rbac.PermClickhouseProcessesList), handlers.ProcessHandler.GetCurrentProcesses)
		processes.GET("/stream", middleware.RequirePermission(rbac.PermClickhouseProcessesStream), handlers.ProcessHandler.StreamProcesses)
		processes.POST("/kill", middleware.RequirePermission(rbac.PermClickhouseProcessesKill), handlers.ProcessHandler.KillProcess)
	}
}

// setupUsersRoutes configures user management endpoints
func setupUsersRoutes(protected *gin.RouterGroup, handlers *handlersContainer) {
	if handlers.UsersHandler == nil {
		return
	}

	users := protected.Group("/clickhouse/users")
	{
		// Register more specific routes first to avoid route conflicts
		users.GET("/details", middleware.RequirePermission(rbac.PermClickhouseUsersDetails), handlers.UsersHandler.UserDetails)
		users.GET("/list", middleware.RequirePermission(rbac.PermClickhouseUsersList), handlers.UsersHandler.GetUsersList)
		users.PUT("/rename", middleware.RequirePermission(rbac.PermClickhouseUsersRename), handlers.UsersHandler.UpdateUserLogin)
		users.PUT("/password", middleware.RequirePermission(rbac.PermClickhouseUsersPassword), handlers.UsersHandler.UpdatePassword)
		users.PUT("/profile", middleware.RequirePermission(rbac.PermClickhouseUsersProfile), handlers.UsersHandler.UpdateProfile)
		users.PUT("/role", middleware.RequirePermission(rbac.PermClickhouseUsersCHRole), handlers.UsersHandler.UpdateRole)
		users.POST("", middleware.RequirePermission(rbac.PermClickhouseUsersCreate), handlers.UsersHandler.CreateUser)
		users.DELETE("", middleware.RequirePermission(rbac.PermClickhouseUsersDelete), handlers.UsersHandler.DeleteUser)
		users.GET("", middleware.RequirePermission(rbac.PermClickhouseUsersGet), handlers.UsersHandler.GetUsers)
	}
}

// setupProfilesRoutes configures profiles endpoints
func setupProfilesRoutes(protected *gin.RouterGroup, handlers *handlersContainer) {
	if handlers.ProfilesHandler == nil {
		return
	}

	profiles := protected.Group("/clickhouse/profiles")
	{
		profiles.GET("/list", middleware.RequirePermission(rbac.PermClickhouseProfilesList), handlers.ProfilesHandler.GetProfilesList)
	}
}

// setupRolesRoutes configures roles endpoints
func setupRolesRoutes(protected *gin.RouterGroup, handlers *handlersContainer) {
	if handlers.RolesHandler == nil {
		return
	}

	roles := protected.Group("/clickhouse/roles")
	{
		roles.GET("/list", middleware.RequirePermission(rbac.PermClickhouseCHRolesList), handlers.RolesHandler.GetRolesList)
	}
}

// setupAccessScopeRoutes configures access scope endpoints
func setupAccessScopeRoutes(protected *gin.RouterGroup, handlers *handlersContainer) {
	if handlers.AccessScopeHandler == nil {
		return
	}

	accessScope := protected.Group("/clickhouse/access-scope")
	{
		accessScope.GET("", middleware.RequirePermission(rbac.PermClickhouseAccessScopeGet), handlers.AccessScopeHandler.GetUserAccessScopes)
		if handlers.UsersHandler != nil {
			accessScope.PUT("", middleware.RequirePermission(rbac.PermClickhouseAccessScopePut), handlers.UsersHandler.UpdateUserAccessScopes)
		}
	}
}

// setupBackupRoutes configures backup endpoints
func setupBackupRoutes(protected *gin.RouterGroup, handlers *handlersContainer) {
	if handlers.BackupHandler == nil {
		return
	}

	backups := protected.Group("/clickhouse/backups")
	{
		backups.GET("/stats", middleware.RequirePermission(rbac.PermClickhouseBackupsStats), handlers.BackupHandler.GetStats)
		backups.GET("/in-progress", middleware.RequirePermission(rbac.PermClickhouseBackupsInProgress), handlers.BackupHandler.GetInProgress)
		backups.GET("/completed", middleware.RequirePermission(rbac.PermClickhouseBackupsCompleted), handlers.BackupHandler.GetCompleted)
		backups.GET("/:id", middleware.RequirePermission(rbac.PermClickhouseBackupsGetByID), handlers.BackupHandler.GetByID)
	}
}

// setupSchemasRoutes configures schemas endpoints
func setupSchemasRoutes(protected *gin.RouterGroup, handlers *handlersContainer) {
	if handlers.SchemasHandler == nil {
		return
	}

	schemas := protected.Group("/clickhouse/schemas")
	{
		schemas.GET("/list", middleware.RequirePermission(rbac.PermClickhouseSchemasList), handlers.SchemasHandler.GetSchemasList)
	}
}

// setupTablesRoutes configures tables endpoints
func setupTablesRoutes(protected *gin.RouterGroup, handlers *handlersContainer) {
	if handlers.TablesHandler == nil {
		return
	}

	tables := protected.Group("/clickhouse/tables")
	{
		tables.GET("/list", middleware.RequirePermission(rbac.PermClickhouseTablesList), handlers.TablesHandler.GetTablesList)
		tables.GET("/stats", middleware.RequirePermission(rbac.PermClickhouseTablesStats), handlers.TablesHandler.GetTablesStats)
		tables.GET("/details/:uuid", middleware.RequirePermission(rbac.PermClickhouseTablesDetails), handlers.TablesHandler.GetTableDetails)
		tables.POST("/:uuid/copy", middleware.RequirePermission(rbac.PermClickhouseTablesCopy), handlers.TablesHandler.CopyTableByUUID)
		tables.DELETE("/:uuid", middleware.RequirePermission(rbac.PermClickhouseTablesDelete), handlers.TablesHandler.DeleteTableByUUID)
	}
}

// setupColumnsRoutes configures columns endpoints
func setupColumnsRoutes(protected *gin.RouterGroup, handlers *handlersContainer) {
	if handlers.ColumnsHandler == nil {
		return
	}

	columns := protected.Group("/clickhouse/columns")
	{
		columns.GET("/list", middleware.RequirePermission(rbac.PermClickhouseColumnsList), handlers.ColumnsHandler.GetColumnsList)
	}
}

// setupSettingsRoutes configures user settings endpoints
func setupSettingsRoutes(protected *gin.RouterGroup, handlers *handlersContainer) {
	if handlers.SettingsHandler == nil {
		return
	}

	settings := protected.Group("/clickhouse/settings")
	{
		if handlers.UsersHandler != nil {
			settings.GET("", middleware.RequirePermission(rbac.PermClickhouseSettingsUserGet), handlers.UsersHandler.GetUserSettings)
			settings.PUT("", middleware.RequirePermission(rbac.PermClickhouseSettingsUserPut), handlers.UsersHandler.UpdateUserSettings)
		}
		settings.GET("/all", middleware.RequirePermission(rbac.PermClickhouseSettingsAll), handlers.SettingsHandler.GetAllSettings)
		settings.GET("/one", middleware.RequirePermission(rbac.PermClickhouseSettingsOne), handlers.SettingsHandler.GetSettingByName)
		settings.GET("/available", middleware.RequirePermission(rbac.PermClickhouseSettingsAvailable), handlers.SettingsHandler.GetAvailableSettings)
	}
}
