package api

import (
	"time"

	"clickhouse-ops/internal/api/auth"
	_ "clickhouse-ops/internal/api/docs" // swagger docs - generated by swag init
	"clickhouse-ops/internal/api/middleware"
	"clickhouse-ops/internal/api/v1/handlers"
	"clickhouse-ops/internal/config"
	"clickhouse-ops/internal/logger"

	"github.com/gin-gonic/gin"
)

// RouterConfig holds router configuration
type RouterConfig struct {
	JWTSecretKey     string
	JWTTokenDuration time.Duration // token duration
	RateLimitRPS     float64
	RateLimitBurst   int
	Logger           *logger.Logger
	Config           *config.Config
}

// RouterWithHandlers holds router and handlers for cleanup in tests
type RouterWithHandlers struct {
	Router          *gin.Engine
	MetricsHandler  *handlers.MetricsHandler
	QueryLogHandler *handlers.QueryLogHandler
	ProcessHandler  *handlers.ProcessHandler
}

// SetupRouter sets up API v1 routes
func SetupRouter(cfg RouterConfig) *gin.Engine {
	router, _ := SetupRouterWithHandlers(cfg)
	return router
}

// SetupRouterWithHandlers sets up API v1 routes and returns handlers for cleanup
func SetupRouterWithHandlers(cfg RouterConfig) (*gin.Engine, *RouterWithHandlers) {
	router := gin.New()

	setupGlobalMiddleware(router, cfg)
	jwtManager := initializeJWTManager(cfg)
	handlers := initializeHandlers(cfg)
	setupRoutes(router, jwtManager, handlers)

	return router, &RouterWithHandlers{
		Router:          router,
		MetricsHandler:  handlers.MetricsHandler,
		QueryLogHandler: handlers.QueryLogHandler,
		ProcessHandler:  handlers.ProcessHandler,
	}
}

// setupGlobalMiddleware configures global middleware for the router
func setupGlobalMiddleware(router *gin.Engine, cfg RouterConfig) {
	// Panic recovery
	router.Use(gin.Recovery())

	// Tracing
	router.Use(middleware.TracingMiddleware())

	// Logging
	router.Use(middleware.LoggingMiddleware(cfg.Logger))

	// Optional rate limiting
	if cfg.RateLimitRPS > 0 {
		rateLimiter := middleware.NewRateLimiter(cfg.RateLimitRPS, cfg.RateLimitBurst)
		router.Use(rateLimiter.RateLimitMiddleware())
	}

	// CORS
	setupCORS(router)
}

// setupCORS configures CORS middleware
func setupCORS(router *gin.Engine) {
	router.Use(func(c *gin.Context) {
		c.Header("Access-Control-Allow-Origin", "*")
		c.Header("Access-Control-Allow-Methods", "GET, POST, PUT, DELETE, OPTIONS")
		c.Header("Access-Control-Allow-Headers", "Content-Type, Authorization, X-Trace-ID")

		if c.Request.Method == "OPTIONS" {
			c.AbortWithStatus(204)
			return
		}

		c.Next()
	})
}

// initializeJWTManager creates and returns JWT manager
func initializeJWTManager(cfg RouterConfig) *auth.JWTManager {
	return auth.NewJWTManager(
		cfg.JWTSecretKey,
		cfg.JWTTokenDuration,
	)
}

// handlersContainer holds all initialized handlers
type handlersContainer struct {
	AuthHandler     *handlers.AuthHandler
	HealthHandler   *handlers.HealthHandler
	MetricsHandler  *handlers.MetricsHandler
	QueryLogHandler *handlers.QueryLogHandler
	ProcessHandler  *handlers.ProcessHandler
	UsersHandler    *handlers.UsersHandler
	BackupHandler   *handlers.BackupHandler
}

// initializeHandlers creates and initializes all handlers
func initializeHandlers(cfg RouterConfig) *handlersContainer {
	container := &handlersContainer{}

	// Initialize auth handler
	authHandler, err := handlers.NewAuthHandler(initializeJWTManager(cfg), cfg.Logger)
	if err != nil {
		cfg.Logger.Errorf("Failed to initialize auth handler: %v", err)
	}
	container.AuthHandler = authHandler

	// Initialize health handler
	container.HealthHandler = handlers.NewHealthHandler()

	// Initialize metrics handler
	metricsHandler, err := handlers.NewMetricsHandler(cfg.Logger, cfg.Config)
	if err != nil {
		cfg.Logger.Errorf("Failed to initialize metrics handler: %v", err)
	}
	container.MetricsHandler = metricsHandler

	// Initialize query log handler
	queryLogHandler, err := handlers.NewQueryLogHandler(cfg.Logger, cfg.Config)
	if err != nil {
		cfg.Logger.Errorf("Failed to initialize query log handler: %v", err)
	}
	container.QueryLogHandler = queryLogHandler

	// Initialize process handler
	processHandler, err := handlers.NewProcessHandler(cfg.Logger, cfg.Config)
	if err != nil {
		cfg.Logger.Errorf("Failed to initialize process handler: %v", err)
	}
	container.ProcessHandler = processHandler

	// Initialize users handler
	usersHandler, err := handlers.NewUsersHandler(cfg.Logger, cfg.Config)
	if err != nil {
		cfg.Logger.Errorf("Failed to initialize users handler: %v", err)
	}
	container.UsersHandler = usersHandler

	// Initialize backup handler
	backupHandler, err := handlers.NewBackupHandler(cfg.Logger, cfg.Config)
	if err != nil {
		cfg.Logger.Errorf("Failed to initialize backup handler: %v", err)
	}
	container.BackupHandler = backupHandler

	return container
}

// setupRoutes configures all API routes
func setupRoutes(router *gin.Engine, jwtManager *auth.JWTManager, handlers *handlersContainer) {
	// Health check endpoint (no auth required)
	if handlers.HealthHandler != nil {
		router.GET("/healthz", handlers.HealthHandler.Healthz)
	}

	// API v1 routes
	v1 := router.Group("/api/v1")
	{
		setupAuthRoutes(v1, jwtManager, handlers)
		setupProtectedRoutes(v1, jwtManager, handlers)
	}
}

// setupAuthRoutes configures authentication routes
func setupAuthRoutes(v1 *gin.RouterGroup, jwtManager *auth.JWTManager, handlers *handlersContainer) {
	if handlers.AuthHandler == nil {
		return
	}

	auth := v1.Group("/auth")
	{
		auth.POST("/login", handlers.AuthHandler.Login)
		auth.POST("/register", handlers.AuthHandler.Register)
		auth.GET("/me", middleware.AuthMiddleware(jwtManager), handlers.AuthHandler.GetUserInfo)
	}
}

// setupProtectedRoutes configures protected API routes
func setupProtectedRoutes(v1 *gin.RouterGroup, jwtManager *auth.JWTManager, handlers *handlersContainer) {
	protected := v1.Group("/")
	protected.Use(middleware.AuthMiddleware(jwtManager))
	{
		setupMetricsRoutes(protected, handlers)
		setupQueryLogRoutes(protected, handlers)
		setupProcessRoutes(protected, handlers)
		setupUsersRoutes(protected, handlers)
		setupBackupRoutes(protected, handlers)
	}
}

// setupMetricsRoutes configures metrics endpoints
func setupMetricsRoutes(protected *gin.RouterGroup, handlers *handlersContainer) {
	if handlers.MetricsHandler == nil {
		return
	}

	metrics := protected.Group("/clickhouse/metrics")
	{
		metrics.GET("/nodes", handlers.MetricsHandler.GetAvailableNodes)
		metrics.GET("/current", handlers.MetricsHandler.GetCurrentMetrics)
		metrics.GET("/stream", handlers.MetricsHandler.StreamMetrics)
		metrics.GET("/series", handlers.MetricsHandler.GetMetricSeries)
		metrics.GET("/server-info", handlers.MetricsHandler.GetServerInfo)
	}
}

// setupQueryLogRoutes configures query log endpoints
func setupQueryLogRoutes(protected *gin.RouterGroup, handlers *handlersContainer) {
	if handlers.QueryLogHandler == nil {
		return
	}

	queryLog := protected.Group("/clickhouse/query-log")
	{
		queryLog.GET("", handlers.QueryLogHandler.ListQueryLog)
		queryLog.GET("/stats", handlers.QueryLogHandler.GetQueryLogStats)
		queryLog.GET("/stats/stream", handlers.QueryLogHandler.StreamQueryLogStats)
	}
}

// setupProcessRoutes configures process management endpoints
func setupProcessRoutes(protected *gin.RouterGroup, handlers *handlersContainer) {
	if handlers.ProcessHandler == nil {
		return
	}

	processes := protected.Group("/clickhouse/processes")
	{
		processes.GET("", handlers.ProcessHandler.GetCurrentProcesses)
		processes.GET("/stream", handlers.ProcessHandler.StreamProcesses)
		processes.POST("/kill", handlers.ProcessHandler.KillProcess)
	}
}

// setupUsersRoutes configures user management endpoints
func setupUsersRoutes(protected *gin.RouterGroup, handlers *handlersContainer) {
	if handlers.UsersHandler == nil {
		return
	}

	users := protected.Group("/clickhouse/users")
	{
		// Register more specific route first to avoid route conflicts
		users.GET("/list", handlers.UsersHandler.GetUsersList)
		users.GET("", handlers.UsersHandler.GetUsers)
	}
}

// setupBackupRoutes configures backup endpoints
func setupBackupRoutes(protected *gin.RouterGroup, handlers *handlersContainer) {
	if handlers.BackupHandler == nil {
		return
	}

	backups := protected.Group("/clickhouse/backups")
	{
		backups.GET("/stats", handlers.BackupHandler.GetStats)
		backups.GET("/in-progress", handlers.BackupHandler.GetInProgress)
		backups.GET("/completed", handlers.BackupHandler.GetCompleted)
		backups.GET("/:id", handlers.BackupHandler.GetByID)
	}
}
