package api

import (
	"time"

	"clickhouse-ops/internal/api/auth"
	_ "clickhouse-ops/internal/api/docs" // swagger docs - generated by swag init
	"clickhouse-ops/internal/api/middleware"
	"clickhouse-ops/internal/api/v1/handlers"
	clickhouseHandlers "clickhouse-ops/internal/api/v1/handlers/clickhouse"
	"clickhouse-ops/internal/config"
	"clickhouse-ops/internal/logger"

	"github.com/gin-gonic/gin"
)

// RouterConfig holds router configuration
type RouterConfig struct {
	JWTSecretKey     string
	JWTTokenDuration time.Duration // token duration
	RateLimitRPS     float64
	RateLimitBurst   int
	Logger           *logger.Logger
	Config           *config.Config
}

// RouterWithHandlers holds router and handlers for cleanup in tests
type RouterWithHandlers struct {
	Router          *gin.Engine
	MetricsHandler  *clickhouseHandlers.MetricsHandler
	QueryLogHandler *clickhouseHandlers.QueryLogHandler
	ProcessHandler  *clickhouseHandlers.ProcessHandler
}

// SetupRouter sets up API v1 routes
func SetupRouter(cfg RouterConfig) *gin.Engine {
	router, _ := SetupRouterWithHandlers(cfg)
	return router
}

// SetupRouterWithHandlers sets up API v1 routes and returns handlers for cleanup
func SetupRouterWithHandlers(cfg RouterConfig) (*gin.Engine, *RouterWithHandlers) {
	router := gin.New()

	setupGlobalMiddleware(router, cfg)
	jwtManager := initializeJWTManager(cfg)
	handlers := initializeHandlers(cfg)
	setupRoutes(router, jwtManager, handlers)

	return router, &RouterWithHandlers{
		Router:          router,
		MetricsHandler:  handlers.MetricsHandler,
		QueryLogHandler: handlers.QueryLogHandler,
		ProcessHandler:  handlers.ProcessHandler,
	}
}

// setupGlobalMiddleware configures global middleware for the router
func setupGlobalMiddleware(router *gin.Engine, cfg RouterConfig) {
	// Panic recovery
	router.Use(gin.Recovery())

	// Tracing
	router.Use(middleware.TracingMiddleware())

	// Logging
	router.Use(middleware.LoggingMiddleware(cfg.Logger))

	// Optional rate limiting
	if cfg.RateLimitRPS > 0 {
		rateLimiter := middleware.NewRateLimiter(cfg.RateLimitRPS, cfg.RateLimitBurst)
		router.Use(rateLimiter.RateLimitMiddleware())
	}

	// CORS
	setupCORS(router)
}

// setupCORS configures CORS middleware
func setupCORS(router *gin.Engine) {
	router.Use(func(c *gin.Context) {
		c.Header("Access-Control-Allow-Origin", "*")
		c.Header("Access-Control-Allow-Methods", "GET, POST, PUT, DELETE, OPTIONS")
		c.Header("Access-Control-Allow-Headers", "Content-Type, Authorization, X-Trace-ID")

		if c.Request.Method == "OPTIONS" {
			c.AbortWithStatus(204)
			return
		}

		c.Next()
	})
}

// initializeJWTManager creates and returns JWT manager
func initializeJWTManager(cfg RouterConfig) *auth.JWTManager {
	return auth.NewJWTManager(
		cfg.JWTSecretKey,
		cfg.JWTTokenDuration,
	)
}

// handlersContainer holds all initialized handlers
type handlersContainer struct {
	AuthHandler        *handlers.AuthHandler
	HealthHandler      *handlers.HealthHandler
	MetricsHandler     *clickhouseHandlers.MetricsHandler
	QueryLogHandler    *clickhouseHandlers.QueryLogHandler
	ProcessHandler     *clickhouseHandlers.ProcessHandler
	UsersHandler       *clickhouseHandlers.UsersHandler
	ProfilesHandler    *clickhouseHandlers.ProfilesHandler
	RolesHandler       *clickhouseHandlers.RolesHandler
	AccessScopeHandler *clickhouseHandlers.AccessScopeHandler
	BackupHandler      *clickhouseHandlers.BackupHandler
	SchemasHandler     *clickhouseHandlers.SchemasHandler
	TablesHandler      *clickhouseHandlers.TablesHandler
	ColumnsHandler     *clickhouseHandlers.ColumnsHandler
	SettingsHandler    *clickhouseHandlers.SettingsHandler
}

// initializeHandlers creates and initializes all handlers
func initializeHandlers(cfg RouterConfig) *handlersContainer {
	container := &handlersContainer{}

	// Initialize auth handler
	authHandler, err := handlers.NewAuthHandler(initializeJWTManager(cfg), cfg.Logger)
	if err != nil {
		cfg.Logger.Errorf("Failed to initialize auth handler: %v", err)
	}
	container.AuthHandler = authHandler

	// Initialize health handler
	container.HealthHandler = handlers.NewHealthHandler()

	// Initialize metrics handler
	metricsHandler, err := clickhouseHandlers.NewMetricsHandler(cfg.Logger, cfg.Config)
	if err != nil {
		cfg.Logger.Errorf("Failed to initialize metrics handler: %v", err)
	}
	container.MetricsHandler = metricsHandler

	// Initialize query log handler
	queryLogHandler, err := clickhouseHandlers.NewQueryLogHandler(cfg.Logger, cfg.Config)
	if err != nil {
		cfg.Logger.Errorf("Failed to initialize query log handler: %v", err)
	}
	container.QueryLogHandler = queryLogHandler

	// Initialize process handler
	processHandler, err := clickhouseHandlers.NewProcessHandler(cfg.Logger, cfg.Config)
	if err != nil {
		cfg.Logger.Errorf("Failed to initialize process handler: %v", err)
	}
	container.ProcessHandler = processHandler

	// Initialize users handler
	usersHandler, err := clickhouseHandlers.NewUsersHandler(cfg.Logger, cfg.Config)
	if err != nil {
		cfg.Logger.Errorf("Failed to initialize users handler: %v", err)
	}
	container.UsersHandler = usersHandler

	// Initialize profiles handler
	profilesHandler, err := clickhouseHandlers.NewProfilesHandler(cfg.Logger, cfg.Config)
	if err != nil {
		cfg.Logger.Errorf("Failed to initialize profiles handler: %v", err)
	}
	container.ProfilesHandler = profilesHandler

	// Initialize roles handler
	rolesHandler, err := clickhouseHandlers.NewRolesHandler(cfg.Logger, cfg.Config)
	if err != nil {
		cfg.Logger.Errorf("Failed to initialize roles handler: %v", err)
	}
	container.RolesHandler = rolesHandler

	// Initialize access scope handler
	accessScopeHandler, err := clickhouseHandlers.NewAccessScopeHandler(cfg.Logger, cfg.Config)
	if err != nil {
		cfg.Logger.Errorf("Failed to initialize access scope handler: %v", err)
	}
	container.AccessScopeHandler = accessScopeHandler

	// Initialize backup handler
	backupHandler, err := clickhouseHandlers.NewBackupHandler(cfg.Logger, cfg.Config)
	if err != nil {
		cfg.Logger.Errorf("Failed to initialize backup handler: %v", err)
	}
	container.BackupHandler = backupHandler

	// Initialize schemas handler
	schemasHandler, err := clickhouseHandlers.NewSchemasHandler(cfg.Logger, cfg.Config)
	if err != nil {
		cfg.Logger.Errorf("Failed to initialize schemas handler: %v", err)
	}
	container.SchemasHandler = schemasHandler

	// Initialize tables handler
	tablesHandler, err := clickhouseHandlers.NewTablesHandler(cfg.Logger, cfg.Config)
	if err != nil {
		cfg.Logger.Errorf("Failed to initialize tables handler: %v", err)
	}
	container.TablesHandler = tablesHandler

	// Initialize columns handler
	columnsHandler, err := clickhouseHandlers.NewColumnsHandler(cfg.Logger, cfg.Config)
	if err != nil {
		cfg.Logger.Errorf("Failed to initialize columns handler: %v", err)
	}
	container.ColumnsHandler = columnsHandler

	// Initialize settings handler
	settingsHandler, err := clickhouseHandlers.NewSettingsHandler(cfg.Logger, cfg.Config)
	if err != nil {
		cfg.Logger.Errorf("Failed to initialize settings handler: %v", err)
	}
	container.SettingsHandler = settingsHandler

	return container
}

// setupRoutes configures all API routes
func setupRoutes(router *gin.Engine, jwtManager *auth.JWTManager, handlers *handlersContainer) {
	// Health check endpoint (no auth required)
	if handlers.HealthHandler != nil {
		router.GET("/healthz", handlers.HealthHandler.Healthz)
	}

	// API v1 routes
	v1 := router.Group("/api/v1")
	{
		setupAuthRoutes(v1, jwtManager, handlers)
		setupProtectedRoutes(v1, jwtManager, handlers)
	}
}

// setupAuthRoutes configures authentication routes
func setupAuthRoutes(v1 *gin.RouterGroup, jwtManager *auth.JWTManager, handlers *handlersContainer) {
	if handlers.AuthHandler == nil {
		return
	}

	auth := v1.Group("/auth")
	{
		auth.POST("/login", handlers.AuthHandler.Login)
		auth.POST("/register", handlers.AuthHandler.Register)
		auth.GET("/me", middleware.AuthMiddleware(jwtManager), handlers.AuthHandler.GetUserInfo)
	}
}

// setupProtectedRoutes configures protected API routes
func setupProtectedRoutes(v1 *gin.RouterGroup, jwtManager *auth.JWTManager, handlers *handlersContainer) {
	protected := v1.Group("/")
	protected.Use(middleware.AuthMiddleware(jwtManager))
	{
		setupMetricsRoutes(protected, handlers)
		setupQueryLogRoutes(protected, handlers)
		setupProcessRoutes(protected, handlers)
		setupUsersRoutes(protected, handlers)
		setupProfilesRoutes(protected, handlers)
		setupRolesRoutes(protected, handlers)
		setupAccessScopeRoutes(protected, handlers)
		setupBackupRoutes(protected, handlers)
		setupSchemasRoutes(protected, handlers)
		setupTablesRoutes(protected, handlers)
		setupColumnsRoutes(protected, handlers)
		setupSettingsRoutes(protected, handlers)
	}
}

// setupMetricsRoutes configures metrics endpoints
func setupMetricsRoutes(protected *gin.RouterGroup, handlers *handlersContainer) {
	if handlers.MetricsHandler == nil {
		return
	}

	metrics := protected.Group("/clickhouse/metrics")
	{
		metrics.GET("/nodes", handlers.MetricsHandler.GetAvailableNodes)
		metrics.GET("/current", handlers.MetricsHandler.GetCurrentMetrics)
		metrics.GET("/stream", handlers.MetricsHandler.StreamMetrics)
		metrics.GET("/series", handlers.MetricsHandler.GetMetricSeries)
		metrics.GET("/server-info", handlers.MetricsHandler.GetServerInfo)
	}
}

// setupQueryLogRoutes configures query log endpoints
func setupQueryLogRoutes(protected *gin.RouterGroup, handlers *handlersContainer) {
	if handlers.QueryLogHandler == nil {
		return
	}

	queryLog := protected.Group("/clickhouse/query-log")
	{
		queryLog.GET("", handlers.QueryLogHandler.ListQueryLog)
		queryLog.GET("/stats", handlers.QueryLogHandler.GetQueryLogStats)
		queryLog.GET("/stats/stream", handlers.QueryLogHandler.StreamQueryLogStats)
	}
}

// setupProcessRoutes configures process management endpoints
func setupProcessRoutes(protected *gin.RouterGroup, handlers *handlersContainer) {
	if handlers.ProcessHandler == nil {
		return
	}

	processes := protected.Group("/clickhouse/processes")
	{
		processes.GET("", handlers.ProcessHandler.GetCurrentProcesses)
		processes.GET("/stream", handlers.ProcessHandler.StreamProcesses)
		processes.POST("/kill", handlers.ProcessHandler.KillProcess)
	}
}

// setupUsersRoutes configures user management endpoints
func setupUsersRoutes(protected *gin.RouterGroup, handlers *handlersContainer) {
	if handlers.UsersHandler == nil {
		return
	}

	users := protected.Group("/clickhouse/users")
	{
		// Register more specific routes first to avoid route conflicts
		users.GET("/details", handlers.UsersHandler.UserDetails)
		users.GET("/list", handlers.UsersHandler.GetUsersList)
		users.PUT("/rename", handlers.UsersHandler.UpdateUserLogin)
		users.PUT("/password", handlers.UsersHandler.UpdatePassword)
		users.PUT("/profile", handlers.UsersHandler.UpdateProfile)
		users.PUT("/role", handlers.UsersHandler.UpdateRole)
		users.POST("", handlers.UsersHandler.CreateUser)
		users.DELETE("", handlers.UsersHandler.DeleteUser)
		users.GET("", handlers.UsersHandler.GetUsers)
	}
}

// setupProfilesRoutes configures profiles endpoints
func setupProfilesRoutes(protected *gin.RouterGroup, handlers *handlersContainer) {
	if handlers.ProfilesHandler == nil {
		return
	}

	profiles := protected.Group("/clickhouse/profiles")
	{
		profiles.GET("/list", handlers.ProfilesHandler.GetProfilesList)
	}
}

// setupRolesRoutes configures roles endpoints
func setupRolesRoutes(protected *gin.RouterGroup, handlers *handlersContainer) {
	if handlers.RolesHandler == nil {
		return
	}

	roles := protected.Group("/clickhouse/roles")
	{
		roles.GET("/list", handlers.RolesHandler.GetRolesList)
	}
}

// setupAccessScopeRoutes configures access scope endpoints
func setupAccessScopeRoutes(protected *gin.RouterGroup, handlers *handlersContainer) {
	if handlers.AccessScopeHandler == nil {
		return
	}

	accessScope := protected.Group("/clickhouse/access-scope")
	{
		accessScope.GET("", handlers.AccessScopeHandler.GetUserAccessScopes)
		if handlers.UsersHandler != nil {
			accessScope.PUT("", handlers.UsersHandler.UpdateUserAccessScopes)
		}
	}
}

// setupBackupRoutes configures backup endpoints
func setupBackupRoutes(protected *gin.RouterGroup, handlers *handlersContainer) {
	if handlers.BackupHandler == nil {
		return
	}

	backups := protected.Group("/clickhouse/backups")
	{
		backups.GET("/stats", handlers.BackupHandler.GetStats)
		backups.GET("/in-progress", handlers.BackupHandler.GetInProgress)
		backups.GET("/completed", handlers.BackupHandler.GetCompleted)
		backups.GET("/:id", handlers.BackupHandler.GetByID)
	}
}

// setupSchemasRoutes configures schemas endpoints
func setupSchemasRoutes(protected *gin.RouterGroup, handlers *handlersContainer) {
	if handlers.SchemasHandler == nil {
		return
	}

	schemas := protected.Group("/clickhouse/schemas")
	{
		schemas.GET("/list", handlers.SchemasHandler.GetSchemasList)
	}
}

// setupTablesRoutes configures tables endpoints
func setupTablesRoutes(protected *gin.RouterGroup, handlers *handlersContainer) {
	if handlers.TablesHandler == nil {
		return
	}

	tables := protected.Group("/clickhouse/tables")
	{
		tables.GET("/list", handlers.TablesHandler.GetTablesList)
	}
}

// setupColumnsRoutes configures columns endpoints
func setupColumnsRoutes(protected *gin.RouterGroup, handlers *handlersContainer) {
	if handlers.ColumnsHandler == nil {
		return
	}

	columns := protected.Group("/clickhouse/columns")
	{
		columns.GET("/list", handlers.ColumnsHandler.GetColumnsList)
	}
}

// setupSettingsRoutes configures user settings endpoints
func setupSettingsRoutes(protected *gin.RouterGroup, handlers *handlersContainer) {
	if handlers.SettingsHandler == nil {
		return
	}

	settings := protected.Group("/clickhouse/settings")
	{
		if handlers.UsersHandler != nil {
			settings.GET("", handlers.UsersHandler.GetUserSettings)
			settings.PUT("", handlers.UsersHandler.UpdateUserSettings)
		}
		settings.GET("/available", handlers.SettingsHandler.GetAvailableSettings)
	}
}
